databaseChangeLog:
    - include:
        file: 001-create-apps-table.yml
        relativeToChangelogFile: true
    - include:
        file: 002-create-repositories-table.yml
        relativeToChangelogFile: true
    - include:
        file: 003-snapshot.yml
        relativeToChangelogFile: true
    - include:
        file: 004-app-auth-key.yml
        relativeToChangelogFile: true